config/routes.rb
Mixture::Application.routes.draw do
  constraints subdomain: 'api' do
    root to: 'application#render_not_found'

    namespace :v0, module: 'api/v0' do
      # Mixes
      resources :mixes, only: [:create, :show, :update] do
        collection do
          get 'popular'
          get 'popular/page/:page', action: :popular

          get 'recent'
          get 'recent/page/:page', action: :recent

          get 'search/:query', action: :search
          get 'search/:query/page/:page', action: :search
        end

        member do
          put 'played', action: :played
          get 'stream', action: :stream
        end
      end

      # Collections
      resources :collections, controller: 'mix_collections', only: [:index, :show] do
        member do
          get 'years'
        end

        collection do
          get 'all'
          get 'page/:page', action: :index
        end

        resources :mixes, only: [:index] do
          get 'page/:page', action: :index, on: :collection
        end
      end

      # Performers
      resources :performers, only: [:index, :show] do
        get 'search', action: :search, on: :collection

        resources :mixes, only: [:index] do
          get 'page/:page', action: :index, on: :collection
        end
      end

      # Users
      resources :users, only: [:create]

      resource :u, controller: 'u', only: [:show] do
        resource :favorites, only: [] do
          collection do
            get '', action: :index
            get 'page/:page', action: :index
          end
          member do
            post ':mix_id', action: :create
            delete ':mix_id', action: :destroy
          end
        end
      end
    end
  end

  namespace :admin do
    root to: redirect('/admin/mixes')
    resources :mixes
    resources :mix_collections
    resources :performers
  end

  get 'search/:query', to: 'mixture#index'
  get 'recent', to: 'mixture#index'
  get 'popular', to: 'mixture#index'
  get 'u/favorites', to: 'mixture#index'
  get 'm/:id', to: 'mixes#show'
  get 'collections', to: 'mixture#index'
  get 'ios', to: 'mixture#index'
  get 'c/:collection_id', to: 'mixture#index'
  root to: 'mixture#index'

  match '*all', to: 'application#render_not_found' unless Rails.application.config.consider_all_requests_local
end

app/models/mix.rb
class Mix
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::MultiParameterAttributes

  attr_accessor :performer_tokens
  attr_reader :performer_tokens

  paginates_per 12

  belongs_to :mix_collection
  has_and_belongs_to_many :performers
  has_many :favorites, order: [[:created_at, :desc]]

  field :caption, type: String
  field :debuted_at, type: DateTime
  field :play_count, type: Integer, default: 0
  field :popluarity_count, type: Integer, default: 0 # play_count + favorite_count
  field :short_url, type: String
  field :duration, type: Integer
  field :sc_url, type: String
  field :sc_id, type: Integer
  field :sc_stream_url, type: String
  field :processing, type: Boolean, default: false
  field :processed_at, type: DateTime

  include Tire::Model::Search
  include Tire::Model::Callbacks

  validates_presence_of :debuted_at, :mix_collection,
                        :performer_ids, :sc_url
  validates_uniqueness_of :sc_url

  default_scope excludes(processed_at: nil)
  scope :popular, order_by(popluarity_count: :desc)
  scope :recent, order_by(created_at: :desc)
  scope :unprocessed, where(processed_at: nil).order_by(:created_at, :desc)

  scope :in_year, ->(year) {
    where(
      :debuted_at.gte => Date.new(year.to_i),
      :debuted_at.lt  => (Date.new(year.to_i) + 1.year)
    )
  }

  # Do this later.
  attr_accessible :caption, :debuted_at, :performer_tokens,
                  :mix_collection_id, :short_url, :sc_url,
                  :processed, :processed_at, as: :admin

  mapping do
    indexes :id,               type: 'string',  index: :not_analyzed
    indexes :caption,          type: 'string',  analyzer: 'snowball', boost: 50
    indexes :play_count,       type: 'integer', index: :not_analyzed
    indexes :popluarity_count, type: 'integer', index: :not_analyzed
    indexes :processed_at, type: 'date', include_in_all: false
    indexes :performers do
      indexes :id, type: 'string', index: :not_analyzed
      indexes :name, type: 'string', analyzer: 'snowball', boost: 50
    end
    indexes :collection do
      indexes :id, type: 'string', index: :not_analyzed
      indexes :name, type: 'string', analyzer: 'snowball', boost: 50
    end
  end

  set_callback :save,   :before, :update_counter_cache, if: :mix_collection_id_changed?
  set_callback :save,   :before, :update_popularity_count

  # Called after cause we need acces to them by there id's in delayed_job
  set_callback :save,   :after, :fetch_soundcloud_data, if: :sc_url_changed?
  set_callback :create, :after, :generate_short_url

  class << self
    def paginate(options = {})
      page(options[:page]).per(options[:per_page])
    end

    def elastic_search(options = {}, role = :default)
      tire.search(load: true, page: options[:page], per_page: (options[:per_page] || 12)) do
        query do
          string options[:query], default_operator: 'AND'
        end

        filter :missing, field: :processed_at if role.equal? :default

        sort do
          by :popluarity_count, 'desc'
        end
      end
    end
  end

  # For Tire
  def to_indexed_json
    {
      id: id,
      performers: performers.map { |p| { id: p.id, name: p.name } },
      mix_collection: { id: mix_collection.id, name: mix_collection.name },
      caption: caption,
      debuted_at: debuted_at,
      created_at: created_at,
      play_count: play_count,
      popluarity_count: popluarity_count
    }.to_json
  end

  def payload(options = {})
    {
      id: id,
      collection: mix_collection,
      performers: performers,
      caption: caption,
      play_count: play_count,
      favorite_count: favorites.count,
      debuted_at: debuted_at.to_i,
      created_at: created_at.to_i,
      duration: duration,
      is_favorite: options[:user].present? ? !options[:user].favorites.where(mix_id: id).empty? : false,
      short_url: short_url
    }
  end

  def as_json(options = {})
    payload options
  end

  def title
    "#{mix_collection.name}#{!caption.blank? ? ' - ' + caption : ''} with #{performers.collect(&:name).join(', ')}"
  end

  alias original_mix_collection= mix_collection=
  def mix_collection=(mix_collection)
    if mix_collection.is_a? Hash
      mix_collection_id = mix_collection['id']
    else
      send :original_mix_collection=, mix_collection
    end
  end

  alias original_performers= performers=
  def performers=(performers)
    # Are the objects returned from ElasticSearch?
    if performers.all? { |p| p.is_a? Hash }
      performer_ids = performers.map { |c| c['id'] }
    else
      send :original_performers=, performers
    end
  end

  def performer_tokens=(ids)
    ids = ids.split(',')

    # Create the new performer if the ID is not an integer
    ids.collect! do |id|
      if BSON::ObjectId.legal?(id)
        id
      else
        id.strip!
        per = Performer.first(conditions: { name: Regexp.new(id, true) })
        per.nil? ? Performer.create!(name: id).id : per.id
      end
    end

    self.performer_ids = ids.uniq
  end

  def played!
    inc(:play_count, 1)
    save
  end

  def streamable_url
    sc_stream_url =~ /\?/ ? "#{sc_stream_url}&client_id=#{ENV['SOUNDCLOUD_CLIENT_ID']}" : "#{sc_stream_url}?client_id=#{ENV['SOUNDCLOUD_CLIENT_ID']}"
  end

  def absolute_url(host = HOST)
    "http://#{host}/m/#{id}"
  end

  def generate_short_url
    Delayed::Job.enqueue(
      ShortenURLJob.new(self.class, id, :short_url, absolute_url),
      queue: 'short_url'
    )
  end

  def processed?
    processed_at.present?
  end

  def fetch_soundcloud_data
    Delayed::Job.enqueue SoundcloudMixDataJob.new(id)
  end

  protected

  def update_counter_cache
    new_mc = MixCollection.find mix_collection_id
    new_mc.inc(:mixes_count, 1)

    if mix_collection_id_was.present?
      old_mc = MixCollection.find mix_collection_id_was
      old_mc.inc(:mixes_count, -1)
    end
  end

  def update_popularity_count
    self.popluarity_count = favorites.count + play_count
  end
end

app/controllers/admin/mixes_controller.rb
class Admin::MixesController < Admin::BaseController
  before_filter :find_mix, only: [:show, :edit, :destroy, :publish, :unpublish, :update, :destroy]

  def index
    if params[:query].present?
      @mixes = Mix.elastic_search({
                                    query: params[:query],
                                    page: params[:page]
                                  }, :admin)
    else
      @mixes = Mix.unscoped.order_by(:debuted_at, :desc).paginate(page: params[:page])
    end
  end

  def new
    @mix = Mix.new
  end

  def show; end

  def edit; end

  def create
    @mix = Mix.new params[:mix], as: :admin
    Rails.logger.info "MIX PARAMS #{params[:mix]}"

    if @mix.save
      redirect_to admin_mix_path(@mix), notice: 'Mix created.'
    else
      render 'new'
    end
  end

  def update
    @mix.assign_attributes(params[:mix], as: :admin)
    if @mix.save
      redirect_to admin_mix_path(@mix), notice: 'Mix has been updated.'
    else
      render :edit
    end
  end

  def destroy
    if @mix.destroy
      redirect_to admin_mixes_path, notice: 'Mix deleted'
    else
      redirect_to admin_mix_path(@mix), notice: 'Problem destroying mix.'
    end
  end

  protected

  def find_mix
    @mix = Mix.unscoped.find(params[:mix_id] || params[:id]) || not_found
  rescue Mongoid::Errors::DocumentNotFound, BSON::InvalidObjectId
    not_found
  end
end

app/controllers/api/v0/mixes_controller.rb
class Api::V0::MixesController < Api::BaseController
  before_filter :authenticate_with_api_key
  before_filter :verify_authenticated_user, only: [:create]

  before_filter lambda {
    find_performer if request.params.include?('performer_id')
  }, only: [:index]

  before_filter lambda {
    find_mix_collection if request.params.include?('collection_id')
  }, only: [:index]

  before_filter :find_mix, only: [:show, :played, :stream]

  def index
    @models = @performer.present? ? @performer.mixes : @mix_collection.mixes
    @models = @models.in_year(params[:year]) unless params[:year].blank?

    @models = @models.order_by([:debuted_at, :desc])
                     .page(params[:page])
                     .per(params[:per_page])

    resp = {
      page: @models.current_page,
      per_page: @models.limit_value,
      total: @models.total_count,
      models: @models
    }

    render json: resp.as_json(user: @current_user)
  end

  def recent
    @models = Mix.recent.page(params[:page]).per(params[:per_page])
    resp = {
      page: @models.current_page,
      per_page: @models.limit_value,
      total: @models.total_count,
      models: @models
    }

    render json: resp.as_json(user: @current_user)
  end

  def popular
    @models = Mix.popular.page(params[:page]).per(params[:per_page])
    resp = {
      page: @models.current_page,
      per_page: @models.limit_value,
      total: @models.total_count,
      models: @models
    }

    render json: resp.as_json(user: @current_user)
  end

  def search
    @results = Mix.elastic_search(params)

    resp = {
      page: @results.current_page,
      per_page: @results.limit_value,
      total: @results.total_count,
      models: @results
    }

    render json: resp.as_json(user: @current_user)
  end

  def show
    render json: @mix.as_json(user: @current_user)
  end

  def played
    @mix.played!
    head :ok
  end

  def stream
    redirect_to @mix.streamable_url
  end
end

app/controllers/mixes_controller.rb
class MixesController < ApplicationController
  before_filter :find_mix, only: [:show]

  def show
    set_meta_tags open_graph: {
      site_name: 'Mixture.fm - Mixes for the Masses',
      title:	@mix.title,
      type: 'mix',
      url: @mix.short_url,
      image: 'http://mixture.fm/assets/fbicon.png'
    }
    render 'mixture/blank'
  end

  protected

  def find_mix
    @mix = Mix.find(params[:id]) || not_found
  rescue Mongoid::Errors::DocumentNotFound, BSON::InvalidObjectId
    not_found
  end
end

app/helpers/mixes_helper.rb
module MixesHelper
end

app/views/admin/mixes/_form.html.erb
<%= content_for :javascript do -%>
	<script type="text/javascript">
		$(function() {
			$("#mix_performer_tokens").tokenInput("/api/v0/performers/search", {
				hintText: "Type in a artist",
				crossDomain: false,
				allowNewItems: true,
				preventDuplicates: true,
				animateDropdown: false
	  	});
		});
	</script>
<% end %>


<%= simple_form_for [:admin, @mix], html: { class: 'form-vertical' } do |f| %>
	<% if f.error_notification %>
		<div class="alert alert-error fade in">
			<a class="close" data-dismiss="alert" href="#">&times;</a>
			<%= f.error_notification %>
		</div>
	<% end %>

	<fieldset>
		<legend>Basic Info</legend>
		<%= f.input :mix_collection_id,
			collection: MixCollection.all,
			selected: @mix.mix_collection.present? ? @mix.mix_collection.id : nil,
			prompt: "-- Select Collection --"
		%>
		<%= f.input :sc_url %>
		<%= f.input :caption %>
		<%= f.input :performer_tokens, input_html: { data: { pre: @mix.performers.to_json } } %>
 		<%= f.input :debuted_at,
			order: [:day, :month, :year],
			:start_year => Date.today.year - 30,
			:end_year => Date.today.year,
			as: :date %>
	</fieldset>

	<div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-primary' %>
    <%= submit_tag 'Cancel', :type => :reset, :class => "btn btn-danger" %>
  </div>
<% end %>

app/views/admin/mixes/_list_item.html.erb
<a id="<%= dom_id(list_item) %>" class="mix" href="<%= admin_mix_path list_item %>">
	<div>
		<h5><%= list_item.title %> <small>( <%= list_item.debuted_at.strftime('%d/%m/%Y') %> )</small></h5>
	</div>
	<div>
		<p class="audio-processing">
			<% if list_item.processed? %>
				<span class="label label-success">Processing complete</span>
			<% else %>
				<% if list_item.processing? %>
					<span class="label label-warning">Processing...</span>
				<% else %>
					<span class="label label-error">Processing failed or is queued for processing.</span>
				<% end %>
			<% end %>
		</p>
	</div>
</a>

app/views/admin/mixes/edit.html.erb
<div class="row-fluid">
  <div class="span12">
    <div class="btn-group pull-right">
      <%= link_to "New Mix", new_admin_mix_path, class: 'btn btn-large' %>
    </div>
  </div>
</div>

<div class="row-fluid">
	<div class="span12">
		<h2>Edit Mix</h2>
		<%= render 'form' %>
	</div>
</div>

app/views/admin/mixes/index.html.erb
<div class="row-fluid">
	<div class="span10">
		<form class="well form-search" method="get" action="<%= admin_mixes_path %>">
  		<input type="text" name="query" class="input-medium search-query">
  		<button type="submit" class="btn">Search</button>
		</form>
	</div>
	<div class="span2">
		<div class="btn-group pull-right">
			<%= link_to "New Mix", new_admin_mix_path, class: 'btn btn-large' %>
		</div>
	</div>
</div>

<div class="row-fluid">
	<div class="span12">
		<div class="mixes">
			<%= render partial: "list_item", collection: @mixes %>
		</div>
	</div>
</div>

<div class="row-fluid">
	<div class="span12">
		<%= paginate @mixes %>
	</div>
</div>

app/views/admin/mixes/new.html.erb
<div class="row-fluid">
  <div class="span12">
    <h2>New Mix</h2>
    <%= render 'form' %>
  </div>
</div>

app/views/admin/mixes/show.html.erb
<div class="row-fluid">
	<div class="span12">
		<div class="btn-group pull-right">
			<%= link_to "New Mix", new_admin_mix_path, class: 'btn btn-large' %>
		</div>
	</div>
</div>

<div class="row-fluid">
	<div class="span12">
		<h2>Processing</h2>
		<p>
			<% if @mix.processed? %>
				<span class="label label-success">Processing complete</span>
			<% else %>
				<% if @mix.processing? %>
					<span class="label label-warning">Processing...</span>
				<% else %>
					<span class="label label-error">Processing failed or is queued for processing.</span>
				<% end %>
			<% end %>
		</p>
		<hr/>
		<h2>
			Basic Info
		</h2>
		<h4>ID</h4>
		<p><%= @mix.id %></p>
		<h4>Collection</h4>
		<p><%= @mix.mix_collection.name %></p>
		<h4>Caption</h4>
		<p><%= @mix.caption %></p>
		<h4>Performers</h4>
		<p><%= @mix.performers.collect { |p| p.name }.join(', ') %></p>
		<h4>Soundcloud URL</h4>
		<p><%= link_to @mix.sc_url, @mix.sc_url, target: '_blank' %></p>
		<h4>Soundcloud Stream URL</h4>
		<p><%= link_to @mix.streamable_url, @mix.streamable_url, target: '_blank' %></p>
		<h4>Soundcloud ID</h4>
		<p><%= link_to @mix.sc_id %></p>
		<h4>Short URL</h4>
		<p><%= link_to @mix.short_url, @mix.short_url, { target: '_blank' } %></p>
		<h4>Debuted</h4>
		<p><%= time_tag @mix.debuted_at %></p>
		<h4>Created</h4>
		<p><%= time_tag @mix.created_at %></p>
		<hr/>

		<div class="well">
			<%= link_to "Edit", edit_admin_mix_path(@mix), class: 'btn btn-small' %>
			<%= link_to "Delete", admin_mix_path(@mix), method: :delete, confirm: "Are you sure?", class: 'btn btn-small btn-danger' %>
		</div>

	</div>
</div>