config/routes.rb
Mixture::Application.routes.draw do
  constraints subdomain: 'api' do
    root to: 'application#render_not_found'

    namespace :v0, module: 'api/v0' do
      # Mixes
      resources :mixes, only: [:create, :show, :update] do
        collection do
          get 'popular'
          get 'popular/page/:page', action: :popular

          get 'recent'
          get 'recent/page/:page', action: :recent

          get 'search/:query', action: :search
          get 'search/:query/page/:page', action: :search
        end

        member do
          put 'played', action: :played
          get 'stream', action: :stream
        end
      end

      # Collections
      resources :collections, controller: 'mix_collections', only: [:index, :show] do
        member do
          get 'years'
        end

        collection do
          get 'all'
          get 'page/:page', action: :index
        end

        resources :mixes, only: [:index] do
          get 'page/:page', action: :index, on: :collection
        end
      end

      # Performers
      resources :performers, only: [:index, :show] do
        get 'search', action: :search, on: :collection

        resources :mixes, only: [:index] do
          get 'page/:page', action: :index, on: :collection
        end
      end

      # Users
      resources :users, only: [:create]

      resource :u, controller: 'u', only: [:show] do
        resource :favorites, only: [] do
          collection do
            get '', action: :index
            get 'page/:page', action: :index
          end
          member do
            post ':mix_id', action: :create
            delete ':mix_id', action: :destroy
          end
        end
      end
    end
  end

  namespace :admin do
    root to: redirect('/admin/mixes')
    resources :mixes
    resources :mix_collections
    resources :performers
  end

  get 'search/:query', to: 'mixture#index'
  get 'recent', to: 'mixture#index'
  get 'popular', to: 'mixture#index'
  get 'u/favorites', to: 'mixture#index'
  get 'm/:id', to: 'mixes#show'
  get 'collections', to: 'mixture#index'
  get 'ios', to: 'mixture#index'
  get 'c/:collection_id', to: 'mixture#index'
  root to: 'mixture#index'

  match '*all', to: 'application#render_not_found' unless Rails.application.config.consider_all_requests_local
end

app/models/performer.rb
class Performer
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug

  field :name, type: String
  slug :name
  paginates_per 20

  has_and_belongs_to_many :mixes

  validates_presence_of :name, message: 'cannot be blank.'
  validates_uniqueness_of :name, message: 'is already taken.', case_sensitive: false

  attr_accessible :name, as: [:default, :admin]
  default_scope order_by(name: 'ASC')

  def payload
    {
      id: id,
      name: name,
      slug: slug
    }
  end

  def as_json(_options = {})
    payload
  end

  class << self
    def simple_search(query = //i)
      where(name: query)
    end

    def paginate(options = {})
      page(options[:page]).per(options[:per_page])
    end
  end
end

app/controllers/admin/performers_controller.rb
class Admin::PerformersController < Admin::BaseController
  before_filter :find_performer, only: [:edit, :update, :show, :destroy]

  def index
    @performers = Performer.order_by(:name, :asc).paginate(page: params[:page])
  end

  def show; end

  def edit; end

  def update
    @performer.assign_attributes params[:performer], as: :admin
    if @performer.save
      redirect_to admin_performer_path(@performer), notice: 'Performer updated.'
    else
      render 'edit'
    end
  end

  def new
    @performer = Performer.new
  end

  def create
    @performer = Performer.new params[:performer], as: :admin
    if @performer.save
      redirect_to admin_performer_path(@performer), notice: 'Performer created.'
    else
      render 'new'
    end
  end

  def destroy
    if @performer.destroy
      redirect_to admin_performers_path, notice: 'Performer deleted'
    else
      redirect_to admin_performer_path(@performer), notice: 'Problem destroying performer.'
    end
  end

  private

  def find_performer
    @performer = Performer.find_by_slug(params[:id]) || not_found
  rescue Mongoid::Errors::DocumentNotFound, BSON::InvalidObjectId
    not_found
  end
end

app/controllers/api/v0/performers_controller.rb
class Api::V0::PerformersController < Api::BaseController
  before_filter :find_performer, only: [:show]

  def index
    # Paginated all the artists we have
    @models = Performer.page(params[:page]).per(params[:per_page])

    resp = {
      page: @models.current_page,
      per_page: @models.limit_value,
      total: @models.total_count,
      models: @models
    }

    render json: resp
  end

  def show
    # Return the info for a single artist
    render json: @performer
  end

  def search
    resp = Performer.simple_search(/#{params[:q]}/i)
    render json: resp
  end
end

app/views/admin/performers/_form.html.erb
<%= simple_form_for [:admin, @performer], html: { class: 'form-vertical' } do |f| %>
	<% if f.error_notification %>
		<div class="alert alert-error fade in">
			<a class="close" data-dismiss="alert" href="#">&times;</a>
			<%= f.error_notification %>
		</div>
	<% end %>

	<fieldset>
		<legend>Basic Info</legend>
		<%= f.input :name %>
	</fieldset>

	<div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-primary' %>
    <%= submit_tag 'Cancel', :type => :reset, :class => "btn btn-danger" %>
  </div>
<% end %>

app/views/admin/performers/_list_item.html.erb
<a id="<%= dom_id(list_item) %>" class="performer clearfix" href="<%= admin_performer_path list_item %>">
	<div class="pull-left">
		<h5><%= list_item.name %></h5>
	</div>
	<div>
		<p class="audio-processing pull-right">
			<%= list_item.mixes.count %> Mixes
		</p>
	</div>
</a>

app/views/admin/performers/edit.html.erb
<h2>Edit Performer</h2>
<%= render 'form' %>

app/views/admin/performers/index.html.erb
<div class="row-fluid">
	<div class="span12">
		<div class="btn-group pull-right">
			<%= link_to "New Performer", new_admin_performer_path, class: 'btn btn-large' %>
		</div>
	</div>
</div>

<div class="row-fluid">
	<div class="span12">
		<div class="performers">
			<%= render partial: "list_item", collection: @performers %>
		</div>
	</div>
</div>

<div class="row-fluid">
	<div class="span12">
		<%= paginate @performers %>
	</div>
</div>

app/views/admin/performers/new.html.erb
<h2>New Performer</h2>
<%= render 'form' %>

app/views/admin/performers/show.html.erb
<div class="row-fluid">
	<div class="span12">
		<h2>Basic Info</h2>

    <h4>ID</h4>
    <p><%= @performer.id %></p>

		<h4>Name</h4>
		<p><%= @performer.name %></p>

    <h4>Mixes</h4>
    <ul class="unstyled">
      <% @performer.mixes.each do |mix| %>
        <%= link_to mix.title, admin_mix_path(mix) %>
      <% end %>
    </ul>

		<div class="well">
			<%= link_to "Edit", edit_admin_performer_path(@performer), class: 'btn btn-small' %>
			<%= link_to "Delete", admin_performer_path(@performer), method: :delete, confirm: "Are you sure?", class: 'btn btn-small btn-danger' %>
		</div>

	</div>
</div>